global:
  image: 'hashicorp/consul-enterprise:1.13.2-ent'
  enterpriseLicense:
    secretName: 'consul-license'
    secretKey: 'key'
  name: consul
  datacenter: dc2-k8s
  enableConsulNamespaces: true
  # enablePodSecurityPolicies: true
  acls:
    manageSystemACLs: true
    # createReplicationToken: true
    replicationToken:
      secretName: consul-federation
      secretKey: replicationToken
  gossipEncryption:
    secretName: consul-federation
    secretKey: gossipEncryptionKey
  # adminPartitions:
  #   enabled: true
  #   name: "default"
  federation:
    enabled: true
    # createFederationSecret: true
    k8sAuthMethodHost: https://consul-quickstart-1664905303353-9c9e701a.hcp.northcentralus.azmk8s.io
    primaryDatacenter: dc1-k8s
    primaryGateways: ["52.151.207.4:443"]

  tls:
    enabled: true
    # enableAutoEncrypt: true
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey

server:
  replicas: 3
  extraVolumes:
    - type: secret
      name: consul-federation
      items:
        - key: serverConfigJSON
          path: config.json
      load: true

client:
  enabled: true
  grpc: true

ui:
  enabled: true
  service:
    type: 'LoadBalancer'

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  default: false
  consulNamespaces:
    mirroringK8s: true

connectInject:
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: false
  # cni:
  #   enabled: true

controller:
  enabled: true

ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer

meshGateway:
  enabled: true
  replicas: 1