apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: counting
spec:
  connectTimeout: 0s
  failover:
    '*':
      service: 'counting'
      datacenters: ['dc1-k8s','dc2-k8s']
  loadBalancer:
    policy: 'round_robin'
